### ISSUE TITLE
Sonar Jacoco report path no longer supported, requires sonar-jacoco plugin

### ISSUE THREAD

**Issue by alphafoobar** [bnc-projects/spring-boot-java-base#68]
<img width="496" alt="Screen Shot 2020-01-27 at 21 08 21" src="https://user-images.githubusercontent.com/4499901/73158622-4092c500-4149-11ea-9245-23a937b156d4.png">

**Comment by bhavikkumar** [comment]
We do not have this set in our build. We use the sonar plugin, not sure why this is being printed out.

**Comment by bhavikkumar** [comment]
I am going to close this, apparently it will require a new plugin for SonarQube
